#import "@jetshop/core/data/fragments/ProductPriceFragment.gql"
#import "@jetshop/core/data/fragments/BadgeFragment.gql"

fragment ProductGrid on Product {
  id
  articleNumber
  name
  subName
  primaryRoute {
    id
    path
    slug
  }
  isPackage
  hidePrice
  ...ProductPrice
  images(limit: 1) {
    alt
    title
    url
    modifiedDate
  }
  badges {
    ...Badge
  }
  canonicalCategory {
    primaryRoute {
      path
    }
  }
  customFields {
    key
    type
    title
    ... on CustomStringField {
      stringValue: value
    }
  }
}
